#!/bin/env bash

# Install Dependencies
sudo yum update
sudo yum install git
sudo amazon-linux-extras install docker -y

# Configure Docker
sudo systemctl enable docker.service
sudo systemctl start docker
sudo usermod -a -G docker ec2-user

# Install docker-compose
wget https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) 
sudo mv docker-compose-$(uname -s)-$(uname -m) /usr/local/bin/docker-compose
sudo chmod -v +x /usr/local/bin/docker-compose

# Setup CI/CD
chmod +x "$HOME/ec2-user"
(crontab -l 2>/dev/null; echo "*/1 * * * * $HOME/deploy") | crontab -
