#!/bin/env bash

GIT_REPO="https://github.com/JFenstermacher/goof-troop-strava"
REPO_HOME="$HOME/goof-troop-strava"

if [ ! -d "$GIT_REPO" ]; then
  git clone "$GIT_REPO" "$REPO_HOME"
fi

cd $REPO_HOME

git pull  # Pull down latest changes
make up   # Docker-compose up
